# docker-compose.yml
services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    env_file:
      - .env
    ports:
      - "${MAIN_PORT:-5000}:${MAIN_PORT:-5000}" # Uses MAIN_PORT from .env, defaults to 5000
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    labels:
      # Router for main Postiz entrypoint (on port 5000)
      - "traefik.http.routers.postiz.rule=Host(`138.199.209.204`)"  # Replace with your domain
      - "traefik.http.services.postiz.loadbalancer.server.port=5000"  # Internal port for postiz
      - "traefik.http.routers.postiz.entrypoints=websecure"  # Postiz requires HTTPS
      - "traefik.http.routers.postiz.tls=true"

  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postiz-password} # Use env var or default
      POSTGRES_USER: ${POSTGRES_USER:-postiz-user}           # Use env var or default
      POSTGRES_DB: ${POSTGRES_DB:-postiz-db-local}           # Use env var or default
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postiz-user} -d ${POSTGRES_DB:-postiz-db-local}"]
      interval: 10s
      timeout: 3s
      retries: 3

  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
  
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
    - postiz-network

volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false
  postiz-uploads:
    external: false

networks:
  postiz-network:
    external: false